version: "3.8"

services:
  mobile:
    build: ./mobile
    volumes:
      - mobile-volume:/mobile
      - tmp-volume:/tmp
      # - ./tmp:/mobile-volume

  api:
    build : ./backend
    container_name : api_backend
    env_file:
      - .env
    volumes:
      - ./backend/data:/app/data
    ports:
      - ${PORT}:${PORT}

volumes:
  mobile-volume:
  tmp-volume:
