@startuml
class Account{
emain: string
name: string
mdp: string
}

class Img{
id: string
name: string
date: date
accountId: string
albumIds: string[]
tags: string[]
}

class Album{
id: string
name: string
creatorAccountId: string
InvitedAccountsIds: string[]
}

Img -up->"accountId" Account
Album "creatorAccountId"-> Account
Album "InvitedAccountsIds"-> Account
Img ->"albumIds" Album
@enduml
